name: workspace setup
on:
  schedule: # execute every 12 hours
    - cron: 0 12 * * *
  workflow_dispatch:
  push:
  pull_request:


jobs:
  env-setup-and-full-build-test:
    runs-on: ubuntu-22.04

    container:
        image: ros:humble-ros-desktop

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y
