name: workspace setup
on:
  schedule: # execute every 12 hours
    - cron: 0 12 * * *
  workflow_dispatch:
  push:
  pull_request:


jobs:
  env-setup-and-full-build-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < roboware.repos
     
      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro humble

      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release
