name: vcs-import

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    container:
      image: ros:humble-ros-base
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pip for rosdep
        run: |
          apt-get -y update && apt-get -y install python3-pip

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < roboware.repos
     
      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro humble
